export { default as Main } from './Main';
export { default as Signup } from './Signup';
export { default as Signin } from './Signin';
export { default as Mint } from './Mint';
export { default as RegisterArtist } from './RegisterArtist';
export { default as NFTcreate } from './NFTcreate';
export { default as NFTlist } from './NFTlist';
export { default as NFTdetail } from './NFTdetail';
export { default as BuyNFT } from './BuyNFT';
