# This is a basic workflow to help you get started with Actions

name: ISLab NearFace - Frontend - Production

# Controls when the action will run.
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install

      - name: Build
        env:
          CI: ''
          REACT_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
          REACT_APP_HOST_DOMAIN: ${{ secrets.VITE_APP_HOST_DOMAIN }}
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 sync ./dist ${{ secrets.AWS_S3_URL }}

      - name: Caching
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_ID }} --paths '/*'
